name: "Create Github checks from code check script output files"
description: "Create Github checks (with annotations for PRs) from JSON file outputs of custom code check scripts"
inputs:
  ghToken:
    description: "Token used to interact with the Github API."
    required: true
  checks:
    description: "JSON array of metadata for each check to annotate"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "check-circle"
  color: "green"



